# api/config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm

    mappings:
        media_object:
            uri_prefix: /mediaObject
            upload_destination: '%kernel.project_dir%/public/mediaObject'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        uploads_Photos:
            uri_prefix: /uploadsPhotos
            upload_destination: '%kernel.project_dir%/public/uploadsPhotos'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer