version: '3.0'
services:

  mysql-solocal:
    container_name: mysql-solocal
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: solocal
      MYSQL_DATABASE: solocal  # Database will be created on start
      MYSQL_USER: solocal    # Password for MySQL User. 
      MYSQL_PASSWORD: solocal
    # We need to run healthcheck because we need to make sure that the initial & default
    # database has been created
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=solocal --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    volumes:
    - ./db:/var/lib/mysql
    networks:
      - solocal

  symfony-solocal:
    container_name: symfony-solocal
    # php7.3
    image: whatwedo/symfony4:v2.0
    # php7.2
    # image: whatwedo/symfony4
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql://solocal:solocal@mysql-solocal:3306/solocal?serverVersion=5.7
    volumes:
    - ./app:/var/www
    # Commande du batch
    #command: php bin/console doctrine:migrations:migrate --no-interaction
    #command: php bin/console --no-interaction doctrine:migrations:migrate -n
    ports:
      - "30:80"
    links:
      - mysql-solocal
    # Database must be ready before running this searvice
    depends_on:
      - mysql-solocal
    tty: true
    networks:
      - solocal

  phpmyadmin-solocal:
    container_name: phpmyadmin-solocal
    image: phpmyadmin/phpmyadmin
    links:
      - mysql-solocal:mysql-solocal
    ports:
      - "31:80"
    networks:
      - solocal
    restart: always
    environment:
      PMA_HOST: mysql-solocal
volumes:
  data:
networks:
  solocal:
